config/routes.rb
Rails.application.routes.draw do
  resources :cashboxes
  resources :rows
  resources :sections
  resources :halls
  root to: 'visitors#index'
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users
  resources :concerts
  resources :tickets
  post 'concert/set_moderated', to: 'concerts#set_moderated'
  post 'cashbox/transfer', to: 'cashboxes#transfer'
  post 'ticket/return', to: 'tickets#return'
  post 'ticket/custom', to: 'row_prices#create'
  get 'tickets/check/:hash', to: 'tickets#check_in', as: :check
end

app/models/hall.rb
class Hall < ActiveRecord::Base
    has_many :sections
end

app/controllers/halls_controller.rb
class HallsController < ApplicationController
  before_action :set_hall, only: [:show, :edit, :update, :destroy]

  # GET /halls
  # GET /halls.json
  def index
    @halls = Hall.all
  end

  # GET /halls/1
  # GET /halls/1.json
  def show
  end

  # GET /halls/new
  def new
    @hall = Hall.new
  end

  # GET /halls/1/edit
  def edit
  end

  # POST /halls
  # POST /halls.json
  def create
    @hall = Hall.new(hall_params)

    respond_to do |format|
      if @hall.save
        format.html { redirect_to @hall, notice: 'Hall was successfully created.' }
        format.json { render :show, status: :created, location: @hall }
      else
        format.html { render :new }
        format.json { render json: @hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /halls/1
  # PATCH/PUT /halls/1.json
  def update
    respond_to do |format|
      if @hall.update(hall_params)
        format.html { redirect_to @hall, notice: 'Hall was successfully updated.' }
        format.json { render :show, status: :ok, location: @hall }
      else
        format.html { render :edit }
        format.json { render json: @hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /halls/1
  # DELETE /halls/1.json
  def destroy
    @hall.destroy
    respond_to do |format|
      format.html { redirect_to halls_url, notice: 'Hall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hall
      @hall = Hall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hall_params
      params[:hall]
    end
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/views/halls/_form.html.erb
<%= simple_form_for(@hall) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/halls/edit.html.erb
<h1>Editing Hall</h1>

<%= render 'form' %>

<%= link_to 'Show', @hall %> |
<%= link_to 'Back', halls_path %>

app/views/halls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Halls</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @halls.each do |hall| %>
      <tr>
        <td><%= link_to 'Show', hall %></td>
        <td><%= link_to 'Edit', edit_hall_path(hall) %></td>
        <td><%= link_to 'Destroy', hall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hall', new_hall_path %>

app/views/halls/new.html.erb
<h1>New Hall</h1>

<%= render 'form' %>

<%= link_to 'Back', halls_path %>

app/views/halls/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hall_path(@hall) %> |
<%= link_to 'Back', halls_path %>