config/routes.rb
Rails.application.routes.draw do
  resources :cashboxes
  resources :rows
  resources :sections
  resources :halls
  root to: 'visitors#index'
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users
  resources :concerts
  resources :tickets
  post 'concert/set_moderated', to: 'concerts#set_moderated'
  post 'cashbox/transfer', to: 'cashboxes#transfer'
  post 'ticket/return', to: 'tickets#return'
  post 'ticket/custom', to: 'row_prices#create'
  get 'tickets/check/:hash', to: 'tickets#check_in', as: :check
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
      <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
        <div class="row"><%= content_tag :div, msg %>
          <a href="#" class="close"></a>
        </div>
      </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Пользователи', users_path %></li>
  <% end %>
  <% if current_user.promoter? || current_user.admin? || current_user.seller? %>
    <li><%= link_to 'Концерты', concerts_path %></li>
  <% end %>
  <% if current_user.seller? ||current_user.admin? || current_user.promoter? %>
    <li><%= link_to 'Билеты', tickets_path %></li>
  <% end %>
  <% if current_user.admin? %>
    <li><%= link_to 'Кассы', cashboxes_path %></li>
  <% end %>
  <li><%= link_to 'Настройки', edit_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar>
    <div class="top-bar-section">
      <ul>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
      <ul class="right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Выйти', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Войти', new_user_session_path %></li>
  <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "S E E B E" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "S E E B E" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      <%= render 'layouts/messages' %>
      <% if controller_name == 'users' %>
        <%= devise_error_messages! %>
      <% end %>
    <main role="main">
    <div class="row">
       <%= yield %>
     </div>
    </main>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-56018864-3', 'auto');
    ga('send', 'pageview');
    </script>
  </body>
</html>