config/routes.rb
Rails.application.routes.draw do
  resources :cashboxes
  resources :rows
  resources :sections
  resources :halls
  root to: 'visitors#index'
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users
  resources :concerts
  resources :tickets
  post 'concert/set_moderated', to: 'concerts#set_moderated'
  post 'cashbox/transfer', to: 'cashboxes#transfer'
  post 'ticket/return', to: 'tickets#return'
  post 'ticket/custom', to: 'row_prices#create'
  get 'tickets/check/:hash', to: 'tickets#check_in', as: :check
end

app/models/row.rb
class Row < ActiveRecord::Base
    belongs_to :section
    has_one :rowPrice
    default_scope { order('number DESC') }
end

app/controllers/rows_controller.rb
class RowsController < ApplicationController
  before_action :set_row, only: [:show, :edit, :update, :destroy]

  # GET /rows
  # GET /rows.json
  def index
    @rows = Row.all
  end

  # GET /rows/1
  # GET /rows/1.json
  def show
  end

  # GET /rows/new
  def new
    @row = Row.new
  end

  # GET /rows/1/edit
  def edit
  end

  # POST /rows
  # POST /rows.json
  def create
    @row = Row.new(row_params)

    respond_to do |format|
      if @row.save
        format.html { redirect_to @row, notice: 'Row was successfully created.' }
        format.json { render :show, status: :created, location: @row }
      else
        format.html { render :new }
        format.json { render json: @row.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rows/1
  # PATCH/PUT /rows/1.json
  def update
    respond_to do |format|
      if @row.update(row_params)
        format.html { redirect_to @row, notice: 'Row was successfully updated.' }
        format.json { render :show, status: :ok, location: @row }
      else
        format.html { render :edit }
        format.json { render json: @row.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rows/1
  # DELETE /rows/1.json
  def destroy
    @row.destroy
    respond_to do |format|
      format.html { redirect_to rows_url, notice: 'Row was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_row
      @row = Row.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def row_params
      params[:row]
    end
end

app/helpers/rows_helper.rb
module RowsHelper
end

app/views/rows/_form.html.erb
<%= simple_form_for(@row) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rows/edit.html.erb
<h1>Editing Row</h1>

<%= render 'form' %>

<%= link_to 'Show', @row %> |
<%= link_to 'Back', rows_path %>

app/views/rows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rows</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rows.each do |row| %>
      <tr>
        <td><%= link_to 'Show', row %></td>
        <td><%= link_to 'Edit', edit_row_path(row) %></td>
        <td><%= link_to 'Destroy', row, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Row', new_row_path %>

app/views/rows/new.html.erb
<h1>New Row</h1>

<%= render 'form' %>

<%= link_to 'Back', rows_path %>

app/views/rows/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_row_path(@row) %> |
<%= link_to 'Back', rows_path %>